name: athome
description: A new Flutter project.


version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  carousel_slider: ^4.2.1
  font_awesome_flutter: ^10.5.0
  ionicons: ^0.2.2
  get: ^4.6.5
  firebase_core: ^2.15.1
  firebase_auth: ^4.9.0
  dio: ^5.3.2
  connectivity_plus: ^4.0.2
  device_info_plus: ^9.0.3
  animate_do: ^3.1.2
  intl_phone_number_input: ^0.7.3+1
  flutter_verification_code: ^1.1.7
  gender_picker: ^1.1.0
  path_provider: ^2.0.11
  encrypt: ^5.0.1
  shared_preferences: ^2.2.1
  fluttertoast: ^8.1.1
  firebase_messaging: ^14.6.8
  cached_network_image: ^3.2.3
  provider: ^6.0.0
  quickalert: ^1.0.2
  skeletonizer: ^0.8.0
  
 



dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


flutter:

  uses-material-design: true

  assets:
    - assets/images/


  fonts:
    - family: Montserrat1
      fonts:
        - asset: assets/fonts/Montserrat/Montserrat-Thin.ttf
          weight: 100 # w100 Thin, the least thick
        - asset: assets/fonts/Montserrat/Montserrat-ThinItalic.ttf
          style: italic
          weight: 100

    - family: Montserrat2
      fonts:          
        - asset: assets/fonts/Montserrat/Montserrat-ExtraLight.ttf
          weight: 200 # w200 Extra-light
        - asset: assets/fonts/Montserrat/Montserrat-ExtraLightItalic.ttf
          style: italic
          weight: 200

    - family: Montserrat3
      fonts:                  
        - asset: assets/fonts/Montserrat/Montserrat-Light.ttf
          weight: 300 # w300 Light
        - asset: assets/fonts/Montserrat/Montserrat-LightItalic.ttf
          style: italic
          weight: 300

    - family: Montserrat4
      fonts:                 
        - asset: assets/fonts/Montserrat/Montserrat-Regular.ttf
          weight: 400 # w400 Normal / regular / plain
        - asset: assets/fonts/Montserrat/Montserrat-Italic.ttf
          style: italic
          weight: 400

    - family: Montserrat5
      fonts:          
        - asset: assets/fonts/Montserrat/Montserrat-Medium.ttf
          weight: 500 # w500 Medium
        - asset: assets/fonts/Montserrat/Montserrat-MediumItalic.ttf
          style: italic
          weight: 500

    - family: Montserrat6
      fonts:          
        - asset: assets/fonts/Montserrat/Montserrat-SemiBold.ttf
          weight: 600 # w600 Semi-bold
        - asset: assets/fonts/Montserrat/Montserrat-SemiBoldItalic.ttf
          style: italic
          weight: 600

    - family: Montserrat7
      fonts:          
        - asset: assets/fonts/Montserrat/Montserrat-Bold.ttf
          weight: 700 # w700 Bold
        - asset: assets/fonts/Montserrat/Montserrat-BoldItalic.ttf
          style: italic
          weight: 700

    - family: Montserrat8
      fonts:          
        - asset: assets/fonts/Montserrat/Montserrat-ExtraBold.ttf
          weight: 800 # w800 Extra-bold
        - asset: assets/fonts/Montserrat/Montserrat-ExtraBoldItalic.ttf
          style: italic
          weight: 800

    - family: Montserrat9
      fonts:          
        - asset: assets/fonts/Montserrat/Montserrat-Black.ttf
          weight: 900 # w900 Black, the most thick
        - asset: assets/fonts/Montserrat/Montserrat-BlackItalic.ttf
          style: italic
          weight: 900