name: dllylas
description: "A new Flutter project."
 
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
 
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'
 
dependencies:
  flutter:
    sdk: flutter


  carousel_slider: ^4.2.1
  font_awesome_flutter: ^10.6.0
  ionicons: ^0.2.2
  get: ^4.6.6
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.3
  dio: ^5.4.0
  connectivity_plus: ^5.0.2
  device_info_plus: ^9.1.1
  animate_do: ^3.1.2
  intl_phone_number_input: ^0.7.4
  flutter_verification_code: ^1.1.7
  gender_picker: ^1.1.0
  path_provider: ^2.1.1
  encrypt: ^5.0.3
  shared_preferences: ^2.2.2
  fluttertoast: ^8.2.4
  firebase_messaging: ^14.7.9
  cached_network_image: ^3.3.0
  provider: ^6.1.1
  quickalert: ^1.0.2
  skeletonizer: ^0.8.0
  geolocator: ^10.1.0
  image_picker: ^1.0.5
  loading_indicator: ^3.1.1
  ntp: ^2.0.0
  http: ^1.1.2
  mapbox_maps_flutter: ^0.5.1  
  flutter_local_notifications: ^16.2.0
  upgrader: ^8.4.0  
  google_fonts: ^6.1.0
  change_app_package_name: ^1.1.0


dev_dependencies:
  flutter_test:
    sdk: flutter
 
  flutter_lints: ^2.0.0
 
flutter:
 
  uses-material-design: true

  assets:
    - assets/images/
    - assets/Victors/
    - assets/images/location.png
    - assets/images/LogoLoading.gif


  fonts:
    - family: nrtB
      fonts:
        - asset: assets/fonts/NRT-Bd.ttf
         

    - family: nrtN
      fonts:          
        - asset: assets/fonts/NRT-Reg.ttf

    - family: spedaB
      fonts:
        - asset: assets/fonts/Speda-Bold.ttf
      
         

    - family: spedaN
      fonts:          
        - asset: assets/fonts/speda.ttf    
        
    - family: iraniB
      fonts:
        - asset: assets/fonts/iraniB.ttf
         

    - family: iraniN
      fonts:          
        - asset: assets/fonts/iraniN.ttf  

