name: dllylas
description: "Dlly Las Online Market."
 
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
 
version: 1.5.0+10

environment:
  sdk: '>=3.2.0 <4.0.0'
 
dependencies:
  flutter:
    sdk: flutter


  carousel_slider: ^4.2.1
  font_awesome_flutter: ^10.7.0
  ionicons: ^0.2.2
  get: ^4.6.6
  firebase_core: ^2.30.0
  dio: ^5.4.3+1
  connectivity_plus: ^6.0.2
  device_info_plus: ^10.1.0
  animate_do: ^3.3.4
  intl_phone_number_input: ^0.7.4
  flutter_verification_code: ^1.1.7
  gender_picker: ^1.1.0
  path_provider: ^2.1.3
  encrypt: ^5.0.3
  shared_preferences: ^2.2.3
  fluttertoast: ^8.2.5
  firebase_messaging: ^14.8.2
  cached_network_image: ^3.3.1
  provider: ^6.1.2
  skeletonizer: ^1.1.1
  geolocator: ^11.0.0
  image_picker: ^1.1.0
  loading_indicator: ^3.1.1
  ntp: ^2.0.0
  http: ^1.2.1
  mapbox_maps_flutter: ^1.1.0 
  flutter_local_notifications: ^17.0.1
  flutter_launcher_icons: ^0.13.1
  cloud_firestore: ^4.16.1
  url_launcher: ^6.2.6
  flutter_dotenv: ^5.1.0
  huawei_push: ^6.12.0+300
  google_nav_bar: ^5.0.6
  line_icons: ^2.0.3
  intl: ^0.19.0
  
  
flutter_launcher_icons:
  #  image_path: "assets/images/icon-128x128.png"
  image_path_android: "assets/images/App-Icon.png"
  android: true # can specify file name here e.g. "ic_launcher"
  ios: false # can specify file name here e.g. "My-Launcher-Icon"
  min_sdk_android: 21 # android min sdk min:16, default 21
  
  

dev_dependencies:
  flutter_test:
    sdk: flutter




  flutter_lints: ^2.0.0
 
flutter:
 
  uses-material-design: true

  assets:
    - .env
    - assets/images/
    - assets/Victors/
    - assets/images/location.png
    - assets/images/LogoLoading.gif
    - assets/images/dllylas.wav


  fonts:
    - family: nrtB
      fonts:
        - asset: assets/fonts/NRT-Bd.ttf
         

    - family: nrtN
      fonts:          
        - asset: assets/fonts/NRT-Reg.ttf

  

