name: athome
description: A new Flutter project.


version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  carousel_slider: ^4.2.1
  font_awesome_flutter: ^10.5.0
  ionicons: ^0.2.2 
  get: ^4.6.5
  firebase_core: ^2.15.1
  firebase_auth: ^4.9.0
  dio: ^5.3.2
  connectivity_plus: ^4.0.2
  device_info_plus: ^9.0.3
  animate_do: ^3.1.2
  intl_phone_number_input: ^0.7.3+1
  flutter_verification_code: ^1.1.7
  gender_picker: ^1.1.0
  path_provider: ^2.0.11
  encrypt: ^5.0.1
  shared_preferences: ^2.2.1
  fluttertoast: ^8.1.1
  firebase_messaging: ^14.6.8
  cached_network_image: ^3.2.3
  provider: ^6.0.0
  skeletonizer: ^0.8.0
  google_maps_flutter: ^2.5.0
  geolocator: ^10.1.0
  panara_dialogs: ^0.1.4
  
  
 



dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


flutter:

  uses-material-design: true

  assets:
    - assets/images/


  fonts:
    - family: nrtB
      fonts:
        - asset: assets/fonts/NRT-Bd.ttf
         

    - family: nrtN
      fonts:          
        - asset: assets/fonts/NRT-Reg.ttf

    - family: spedaB
      fonts:
        - asset: assets/fonts/Speda-Bold.ttf
         

    - family: spedaN
      fonts:          
        - asset: assets/fonts/speda.ttf    
        
    - family: iraniB
      fonts:
        - asset: assets/fonts/iraniB.ttf
         

    - family: iraniN
      fonts:          
        - asset: assets/fonts/iraniN.ttf  

