name: dllylas
description: "Dlly Las Online Market."
 
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
 
version: 1.1.0+6

environment:
  sdk: '>=3.2.0 <4.0.0'
 
dependencies:
  flutter:
    sdk: flutter


  carousel_slider: ^4.2.1
  font_awesome_flutter: ^10.6.0
  ionicons: ^0.2.2
  get: ^4.6.6
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.3
  dio: ^5.4.0
  connectivity_plus: ^5.0.2
  device_info_plus: ^9.1.1
  animate_do: ^3.1.2
  intl_phone_number_input: ^0.7.4
  flutter_verification_code: ^1.1.7
  gender_picker: ^1.1.0
  path_provider: ^2.1.1
  encrypt: ^5.0.3
  shared_preferences: ^2.2.2
  fluttertoast: ^8.2.4
  firebase_messaging: ^14.7.9
  cached_network_image: ^3.3.0
  provider: ^6.1.1
  quickalert: ^1.0.2
  skeletonizer: ^0.8.0
  geolocator: ^10.1.0
  image_picker: ^1.0.5
  loading_indicator: ^3.1.1
  ntp: ^2.0.0
  flutter_kronos: ^0.1.0+1
  http: ^1.1.2
  mapbox_maps_flutter: ^0.5.1  
  flutter_local_notifications: ^16.2.0
  upgrader: ^8.4.0  
  google_fonts: ^6.1.0
  change_app_package_name: ^1.1.0
  flutter_launcher_icons: ^0.13.1
  cloud_firestore: ^4.13.6
  url_launcher: ^6.2.2
  flutter_dotenv: ^5.1.0
  audioplayers: ^5.2.1
  huawei_push: ^6.11.0+300
  
flutter_launcher_icons:
  #  image_path: "assets/images/icon-128x128.png"
  image_path_android: "assets/images/App-Icon.png"
  android: true # can specify file name here e.g. "ic_launcher"
  ios: false # can specify file name here e.g. "My-Launcher-Icon"
  min_sdk_android: 21 # android min sdk min:16, default 21
  
  

dev_dependencies:
  flutter_test:
    sdk: flutter




  flutter_lints: ^2.0.0
 
flutter:
 
  uses-material-design: true

  assets:
    - .env
    - assets/images/
    - assets/Victors/
    - assets/images/location.png
    - assets/images/LogoLoading.gif
    - assets/images/dllylas.wav


  fonts:
    - family: nrtB
      fonts:
        - asset: assets/fonts/NRT-Bd.ttf
         

    - family: nrtN
      fonts:          
        - asset: assets/fonts/NRT-Reg.ttf

  

